sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anajji/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anajji/react-test npm run test

after_success:
  - docker build -t anajji/multi-client ./client
  - docker build -t anajji/multi-nginx ./nginx
  - docker build -t anajji/multi-server ./server
  - docker build -t anajji/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin

  - docker push anajji/multi-client
  - docker push anajji/multi-nginx
  - docker push anajji/multi-server
  - docker push anajji/multi-worker
